var ndata = [
    {"id": 0},
    {"id": 1},
    {"id": 2},
    {"id": 3},
    {"id": 4},
    {"id": 5},
]

var ldata0 = [
    [],
]
var ldata1 = [
    [{'source': 0, 'target': 1}],
]
var ldata2 = [
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}],
    [{'source': 0, 'target': 3}, {'source': 1, 'target': 2}],
]
var ldata3 = [
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 1, 'target': 2}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 3}, {'source': 1, 'target': 2}],
    [{'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 1, 'target': 2}],
    [{'source': 0, 'target': 5}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
]
var ldata4 = [
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 1, 'target': 2}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 1, 'target': 2}],
    [{'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 4}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}],
    [{'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}],
    [{'source': 0, 'target': 4}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 5}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
]
var ldata5 = [
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 1, 'target': 2}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 4}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 4}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 5}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 5}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 1, 'target': 2}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 3}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}],
]
var ldata6 = [
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 4}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 5}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 1, 'target': 2}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 3}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 3}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 5}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 3, 'target': 4}],
]
var ldata7 = [
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 1, 'target': 2}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 3}, {'source': 0, 'target': 5}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 3}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 3}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 3}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 5}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 3, 'target': 4}],
]
var ldata8 = [
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 5}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 3}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 3}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 3}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 5}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 3}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 3, 'target': 4}],
]
var ldata9 = [
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 3}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 2, 'target': 5}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 5}, {'source': 3, 'target': 4}],
]
var ldata10 = [
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 2, 'target': 5}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 5}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 5}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 5}, {'source': 3, 'target': 4}],
]
var ldata11 = [
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 2, 'target': 5}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 5}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 5}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 5}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 2, 'target': 5}, {'source': 3, 'target': 4}],
]
var ldata12 = [
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 2, 'target': 5}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 5}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 2, 'target': 5}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 4}, {'source': 2, 'target': 5}, {'source': 3, 'target': 4}, {'source': 3, 'target': 5}],
]
var ldata13 = [
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 2, 'target': 5}, {'source': 3, 'target': 4}],
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 4}, {'source': 2, 'target': 5}, {'source': 3, 'target': 4}, {'source': 3, 'target': 5}],
]
var ldata14 = [
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 2, 'target': 5}, {'source': 3, 'target': 4}, {'source': 3, 'target': 5}],
]
var ldata15 = [
    [{'source': 0, 'target': 1}, {'source': 0, 'target': 2}, {'source': 0, 'target': 3}, {'source': 0, 'target': 4}, {'source': 0, 'target': 5}, {'source': 1, 'target': 2}, {'source': 1, 'target': 3}, {'source': 1, 'target': 4}, {'source': 1, 'target': 5}, {'source': 2, 'target': 3}, {'source': 2, 'target': 4}, {'source': 2, 'target': 5}, {'source': 3, 'target': 4}, {'source': 3, 'target': 5}, {'source': 4, 'target': 5}],
]
